#!/bin/bash

echo "Chat Frontend - 依赖安装脚本"
echo "================================"
echo ""
echo "由于系统没有npm，请按照以下步骤手动安装依赖："
echo ""
echo "1. 确保已安装Node.js (版本 >= 16.0.0)"
echo "2. 在项目根目录下运行以下命令："
echo ""
echo "npm install"
echo ""
echo "或者使用yarn："
echo ""
echo "yarn install"
echo ""
echo "依赖列表："
echo "- vue@^3.3.0"
echo "- vue-router@^4.2.0"
echo "- pinia@^2.1.0"
echo "- axios@^1.4.0"
echo "- element-plus@^2.3.0"
echo "- @element-plus/icons-vue@^2.1.0"
echo "- sass@^1.62.0"
echo "- @types/node@^20.0.0"
echo "- @vitejs/plugin-vue@^4.2.0"
echo "- vite@^4.3.0"
echo "- typescript@^5.0.0"
echo "- vue-tsc@^1.6.0"
echo "- electron@^25.0.0"
echo "- electron-builder@^24.0.0"
echo "- vite-plugin-electron@^0.12.0"
echo "- vite-plugin-electron-renderer@^0.14.0"
echo ""
echo "开发依赖："
echo "- @typescript-eslint/eslint-plugin@^5.59.0"
echo "- @typescript-eslint/parser@^5.59.0"
echo "- @vue/eslint-config-prettier@^7.1.0"
echo "- @vue/eslint-config-typescript@^11.0.0"
echo "- @vue/tsconfig@^0.4.0"
echo "- eslint@^8.42.0"
echo "- eslint-plugin-vue@^9.14.0"
echo "- prettier@^2.8.0"
echo ""
echo "安装完成后，可以使用以下命令启动项目："
echo ""
echo "开发模式："
echo "npm run dev"
echo ""
echo "构建Web版本："
echo "npm run build"
echo ""
echo "构建Electron版本："
echo "npm run electron:build"
echo ""
echo "预览构建结果："
echo "npm run preview"
